### PR TITLE
add zabbix_proxy_package_state  var

### PR DESCRIPTION
**Pull request by ghost**
**Description of PR**

**Type of change**

Feature Pull Request
Bugfix Pull Request
Docs Pull Request

**Fixes an issue**

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @zab35 

Thank you for creating a PR, but I would suggest to add this change to the #42 PR as this change is related and is part of the same functionality.

**Comment by ghost** [comment]
> 
> 
> Hi @zab35
> 
> Thank you for creating a PR, but I would suggest to add this change to the #42 PR as this change is related and is part of the same functionality.

Hi @dj-wasabi 
How can i add this change to the #42 ? Is it this possible through the web interface ?

**Comment by dj-wasabi** [comment]
Hi @zab35 

I don't know if the webinterface is able to do that. I do this from the commandline.
But, will merge the PR's tonight and make sure it will work. Thanks! 👍

**Comment by ghost** [comment]
> But, will merge the PR's tonight and make sure it will work. Thanks!

Thanks :) , can you create a new tag after that?

**Comment by dj-wasabi** [comment]
@zab35  Yeah sure, will do that! Will let you know.

**Comment by dj-wasabi** [comment]
@zab35 I uploaded version 1.4.0 to the Galaxy! Have fun! 😄

**Pull request merged**
