### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by hatifnatt**
Thanks for this role! Unfortunately it doesn't work "out of the box" in my case, so I made few improvements.

- Added parameter `zabbix_proxy_hostname`  which allow customization of proxy `Hostname` parameter. Backward compatibility preserved if `zabbix_proxy_hostname` not specified `inventory_hostname` will be used as before.
- Improved conditional checks:
  - Do not install any DB related packages if db is not created or schema imported.
  - Install PostgreSQL related packages only if database_type == 'pgsql'
- Do not create "done file" if we are not importing schema. 
- Fixed tags

### CODE REVIEW

**Comment by hatifnatt** [comment]
I think this failed check does not related to PR code changes.

**Comment by dj-wasabi** [comment]
Hi @hatifnatt 

Sorry for late answer/reply, but could you please take a look at the conflicts and resolve them? When resolved I'm able to merge it.

Thanks!

Kind regards,
Werner

**Comment by hatifnatt** [comment]
I hope conflicts are resolved now. Also small fixup at [line 34](https://github.com/dj-wasabi/ansible-zabbix-proxy/pull/26/commits/6e910a14eb421eea1ac93c03dcfd99615f2f661e#diff-4c10249465c8c3ea2aea231493decd8dL34).

**Comment by dj-wasabi** [comment]
Thanks! 👍

**Pull request merged**
