### PR TITLE
Adding zabbix_proxy_install_database_client variable

### PR DESCRIPTION
**Pull request by rnsc**
**Description of PR**

This PR adds a new variable so that we can ignore the installation of the database client so that the proxy roles behaves the same way as the server role.

**Type of change**

Feature Pull Request

### CODE REVIEW

**Comment by rnsc** [comment]
Looks like I missed the RedHat.yml file :)

**Comment by rnsc** [comment]
Updated RedHat.yml with the new variable also.

**Comment by dj-wasabi** [comment]
Hi @rnsc 

Can you also update the readme and provide a small description what `zabbix_proxy_install_database_client ` does?

Thanks!

**Comment by rnsc** [comment]
> Hi @rnsc
> 
> Can you also update the readme and provide a small description what `zabbix_proxy_install_database_client ` does?
> 
> Thanks!

Done. :)

**Comment by dj-wasabi** [comment]
Thanks! 👍

**Comment by rnsc** [comment]
@dj-wasabi small question, how often do you release to ansible galaxy?
Thank you for creating those zabbix roles btw, they’re great!
I might create another pull request to optimise the windows one.

**Comment by dj-wasabi** [comment]
I don't have any release schedule, I do release when I feel a need for it or when someone ask for a release. So if you want a new release of the proxy, I can arrange that. 😄

**Comment by rnsc** [comment]
@dj-wasabi would be cool to have a release for this, I'm using Ansible galaxy to setup my local env and right now, I have this custom version in place, but I'd rather have a clean version from Ansible galaxy. :)
Thanks :)

**Comment by dj-wasabi** [comment]
Hi @rnsc 

I uploaded 1.3.0 to the Galaxy! Have fun! 😄

**Comment by rnsc** [comment]
@dj-wasabi thank you very much sir! I'm having fun alright! :smile:

**Pull request merged**
