### PR TITLE
Molecule test

### PR DESCRIPTION
**Pull request by dj-wasabi**
Adding molecule tests and removing test-kitchen tests.

### CODE REVIEW

**Comment by retr0h** [comment]
@dj-wasabi looking into your failure.  I thought we fixed this, it was a bug that occurs with ansible 2.1.1.

**Comment by dj-wasabi** [comment]
Hi @retr0h I have on my local machine molecule 1.9.0 and Ansible 2.1.1.0 installed and there it works...

**Comment by retr0h** [comment]
> Hi @retr0h I have on my local machine molecule 1.9.0 and Ansible 2.1.1.0 installed and there it works...

Do you have a custom ansible.cfg on your local system that could be changing the path to where it finds the roles?  I'm trying to hunt down the source of the problem.

Also, my apologies for causing issues.  Was hoping 1.9 would be a seamless upgrade.

**Comment by retr0h** [comment]
While, I am working on a fix, you will also want to update your testinfra tests with [this](https://github.com/metacloud/molecule/blob/master/test/functional/driver/docker/scenarios/command_test/tests/test_default.py#L1-L3).

`molecule init` adds these to the tests created, however, you have tests created pre-1.9.  This will allow you to target groups which the vagrant backend would let you do.  Unfortunately is a limitation of testinfra's docker backend.

**Comment by retr0h** [comment]
@dj-wasabi While I fix molecule you can update your molecule.yml with the following.  This should work-a-round the issue for now.

```
ansible:
  raw_env_vars:
    ANSIBLE_ROLES_PATH: .molecule/roles:../.molecule/roles:../:../../
```

**Comment by dj-wasabi** [comment]
@retr0h 

No worries mate ;-)

I only have the one in the root of this repository which is the one called from `molecule.yml`:

```
[defaults]
roles_path = ../:../../
hostfile = tests/inventory
```

It worked locally, because the roles where already found in the roles_path. I deleted the dependency roles and now I get the same error as on Travis.

But when running the `molecule converge` step locally doesn't download the roles, but it did on travis..

**Comment by retr0h** [comment]
Don't forget to update your tests as I indicated in a [few comments above](https://github.com/dj-wasabi/ansible-zabbix-proxy/pull/5#issuecomment-241823539), and you should be green.

**Comment by dj-wasabi** [comment]
Yes, I see it. (Sorry, I've already created an issue for this. Will close it.)

Thank you!

**Comment by retr0h** [comment]
I believe I fixed the issues you ran into.  1.9.1 was pushed to [pypi](https://pypi.python.org/pypi/molecule).

**Comment by dj-wasabi** [comment]
@retr0h Thanks again!

**Pull request merged**
